const QUESTIONS = [
 {id:"fn1",topic:"Functions",difficulty:"Warm-up",type:"mc",prompt:"If f(x) = 3x − 4, what is f(5)?",choices:["8","11","15","19"],answer:"11",lesson:"Function notation is a substitution instruction. Replace every x with the input. Example: if g(x)=2x+1, then g(4)=2(4)+1=9. For this problem, substitute 5 for x.",explanation:"f(5)=3(5)−4=11.",mistake:"Substitution error"},
 {id:"fn2",topic:"Functions",difficulty:"Medium",type:"mc",prompt:"Compared with y = x², how is y = (x − 3)² + 2 transformed?",choices:["Left 3, down 2","Right 3, up 2","Right 2, up 3","Left 2, down 3"],answer:"Right 3, up 2",lesson:"In y=(x−h)²+k, h moves the graph horizontally (opposite the sign you see) and k moves it vertically. Example: (x+4)²−1 goes left 4 and down 1.",explanation:"The −3 inside shifts right 3; +2 outside shifts up 2.",mistake:"Misread transformation"},
 {id:"q1",topic:"Quadratics",difficulty:"Warm-up",type:"mc",prompt:"What are the solutions to x² − 5x + 6 = 0?",choices:["1 and 6","2 and 3","−2 and −3","0 and 6"],answer:"2 and 3",lesson:"To factor x²+bx+c, find two numbers that multiply to c and add to b. Example: x²−7x+12=(x−3)(x−4), so x=3 or 4.",explanation:"(x−2)(x−3)=0, so x=2 or x=3.",mistake:"Factoring error"},
 {id:"q2",topic:"Quadratics",difficulty:"Honors",type:"text",prompt:"For 2x² − 5x + 7 = 0, how many real solutions are there?",answer:["0","zero","no real solutions","none"],lesson:"Use the discriminant b²−4ac. Positive means 2 real roots, zero means 1, and negative means no real roots. Example: x²+2x+5 has 4−20<0, so no real roots.",explanation:"The discriminant is (−5)²−4(2)(7)=−31, so there are 0 real solutions.",mistake:"Discriminant error"},
 {id:"c1",topic:"Complex Numbers",difficulty:"Medium",type:"mc",prompt:"Simplify i¹⁸.",choices:["1","−1","i","−i"],answer:"−1",lesson:"Powers of i repeat every four: i, −1, −i, 1. Divide the exponent by 4 and use the remainder. 10 leaves remainder 2, so i¹⁰=i²=−1.",explanation:"18 leaves remainder 2 when divided by 4, so i¹⁸=i²=−1.",mistake:"Power cycle error"},
 {id:"p1",topic:"Polynomials",difficulty:"Medium",type:"mc",prompt:"What is the remainder when p(x)=x³−2x+5 is divided by x−2?",choices:["1","5","7","9"],answer:"9",lesson:"The Remainder Theorem says the remainder after dividing p(x) by x−a is p(a). Example: for x²+1 divided by x−3, the remainder is 3²+1=10.",explanation:"p(2)=8−4+5=9.",mistake:"Evaluation error"},
 {id:"p2",topic:"Polynomials",difficulty:"Honors",type:"tf",prompt:"True or false: A zero with even multiplicity makes a polynomial graph cross the x-axis.",choices:["True","False"],answer:"False",lesson:"At odd-multiplicity zeros, a graph crosses the axis. At even-multiplicity zeros, it touches and turns. Think of y=x² touching at zero versus y=x³ crossing.",explanation:"False. Even multiplicity touches and turns; odd multiplicity crosses.",mistake:"Multiplicity confusion"},
 {id:"r1",topic:"Rational Functions",difficulty:"Medium",type:"mc",prompt:"Simplify (x² − 9)/(x − 3), where x ≠ 3.",choices:["x − 3","x + 3","x² + 3","1"],answer:"x + 3",lesson:"Factor before canceling. A difference of squares a²−b²=(a−b)(a+b). Example: (x²−16)/(x−4)=x+4, while x=4 remains excluded.",explanation:"Factor as (x−3)(x+3), then cancel x−3. The restriction x≠3 remains.",mistake:"Domain restriction"},
 {id:"r2",topic:"Rational Functions",difficulty:"Honors",type:"mc",prompt:"What feature does f(x)=(x−2)/((x−2)(x+1)) have at x=2?",choices:["Vertical asymptote","Hole","x-intercept","No special feature"],answer:"Hole",lesson:"A factor that cancels creates a hole at its zero. A denominator factor that remains creates a vertical asymptote. Example: (x−4)/((x−4)(x+2)) has a hole at x=4.",explanation:"The x−2 factor cancels, so x=2 is a hole.",mistake:"Asymptote/hole confusion"},
 {id:"rad1",topic:"Radicals",difficulty:"Medium",type:"mc",prompt:"Simplify √72.",choices:["6√2","12√6","8√9","3√8"],answer:"6√2",lesson:"Look for the largest perfect-square factor. Example: √50=√(25·2)=5√2. Here, find a perfect square inside 72.",explanation:"72=36·2, so √72=6√2.",mistake:"Radical simplification"},
 {id:"e1",topic:"Exponential Functions",difficulty:"Warm-up",type:"text",prompt:"Solve 3 · 2ˣ = 48.",answer:["4","x=4","x = 4"],lesson:"Isolate the exponential expression, then match powers with the same base. Example: 5·3ˣ=135 gives 3ˣ=27=3³, so x=3.",explanation:"Divide by 3: 2ˣ=16=2⁴, so x=4.",mistake:"Exponent rule error"},
 {id:"log1",topic:"Logarithms",difficulty:"Medium",type:"mc",prompt:"Rewrite log₂(32)=5 in exponential form.",choices:["5²=32","2⁵=32","32²=5","2³²=5"],answer:"2⁵=32",lesson:"logₐ(b)=c means aᶜ=b. The base stays the base. Example: log₃(81)=4 becomes 3⁴=81.",explanation:"The base 2 raised to the exponent 5 equals 32.",mistake:"Log form confusion"},
 {id:"s1",topic:"Sequences",difficulty:"Warm-up",type:"text",prompt:"Find the 8th term of the arithmetic sequence 5, 8, 11, …",answer:["26","a8=26","a₈=26"],lesson:"For an arithmetic sequence, aₙ=a₁+(n−1)d. Example: 2,7,12,… has a₆=2+5(5)=27.",explanation:"a₈=5+(8−1)(3)=26.",mistake:"Sequence formula error"},
 {id:"sys1",topic:"Systems",difficulty:"Medium",type:"mc",prompt:"Solve: y=2x+1 and y=−x+7.",choices:["(2, 5)","(3, 7)","(1, 3)","(4, 9)"],answer:"(2, 5)",lesson:"At an intersection, both y-expressions are equal. Set them equal, solve for x, then substitute. Example: y=x+2 and y=−x+6 gives x=2, y=4.",explanation:"2x+1=−x+7 gives x=2 and y=5.",mistake:"System substitution error"},
 {id:"t1",topic:"Trigonometry",difficulty:"Honors",type:"mc",prompt:"Convert 150° to radians.",choices:["π/6","5π/6","3π/2","5π/3"],answer:"5π/6",lesson:"Multiply degrees by π/180 and simplify. Example: 60°·π/180=π/3.",explanation:"150·π/180=5π/6.",mistake:"Degree/radian conversion"}
];
const KEY="algebraGlowUpDataV2";
const GENERATOR_VERSION=18;
let data=load(), exam=null, timerId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function defaultData(){return{profile:{},history:[],draft:null,generatorLog:{usedPromptKeys:[],sessionCounter:0}}}
function shapeData(saved){saved=saved||defaultData();saved.profile=saved.profile||{};saved.history=Array.isArray(saved.history)?saved.history:[];saved.generatorLog=saved.generatorLog||{};saved.generatorLog.usedPromptKeys=Array.isArray(saved.generatorLog.usedPromptKeys)?saved.generatorLog.usedPromptKeys:[];saved.generatorLog.sessionCounter=Number(saved.generatorLog.sessionCounter)||0;if(saved.draft&&saved.draft.generatorVersion!==GENERATOR_VERSION)saved.draft=null;return saved}
function load(){try{return shapeData(JSON.parse(localStorage.getItem(KEY))||defaultData())}catch{return defaultData()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function normalize(v){return String(v??"").toLowerCase().replace(/\s/g,"").replace(/[−–]/g,"-").replace(/[₀-₉]/g,c=>"₀₁₂₃₄₅₆₇₈₉".indexOf(c))}
function questionKey(q){return normalize(`${q.topic}|${q.difficulty}|${q.prompt}`)}
function rememberQuestionSet(questions){data=shapeData(data);let keys=data.generatorLog.usedPromptKeys,seen=new Set(keys);questions.forEach(q=>{let key=questionKey(q);if(!seen.has(key)){keys.push(key);seen.add(key)}});data.generatorLog.usedPromptKeys=keys.slice(-900);save()}
function isCorrect(q,a){return Array.isArray(q.answer)?q.answer.some(x=>normalize(x)===normalize(a)):normalize(q.answer)===normalize(a)}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function grade(p){return p>=93?"A":p>=90?"A−":p>=87?"B+":p>=83?"B":p>=80?"B−":p>=77?"C+":p>=73?"C":p>=70?"C−":p>=60?"Needs review":"Reteach needed"}
function showView(name){$$(".view").forEach(v=>v.classList.add("hidden"));$(`#${name}View`).classList.remove("hidden");$$("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="dashboard")renderDashboard();if(name==="admin")renderAdmin();if(name==="home")updateResumeButton();scrollTo(0,0)}
function updateResumeButton(){let b=$("#resumeExam");if(b)b.classList.toggle("hidden",!data.draft)}
function resumeExam(){if(!data.draft){toast("No saved test yet.");return}exam=data.draft;applyProfile();showView("exam");$("#examStudent").textContent=data.profile.voice==="bestie"?`${data.profile.name||"Bestie"}, let's finish this.`:`${data.profile.name||"Student"}'s saved exam`;renderQuestion();startTimer()}
const ADMIN_EMAILS=(window.APP_ADMIN_EMAILS||[]).map(e=>e.toLowerCase());
let fb=null,authUser=null,account=null,functionsApi=null,accountUnsub=null;
function firebaseConfigured(){return window.firebase&&window.FIREBASE_CONFIG&&!String(window.FIREBASE_CONFIG.apiKey||"").includes("PASTE_")}
function callFn(name,data={}){if(!functionsApi)throw new Error("Firebase Functions are not ready.");return functionsApi.httpsCallable(name)(data).then(r=>r.data)}
function showAuthMessage(msg){let el=$("#authMessage");if(el)el.textContent=msg}
function setAuthGate(show){let gate=$("#authGate");if(!gate)return;gate.classList.toggle("hidden",!show);gate.style.display=show?"grid":"none";gate.setAttribute("aria-hidden",show?"false":"true");$("#signOutButton")?.classList.toggle("hidden",show)}
function renderAccount(){let email=authUser?.email||"",isAdmin=ADMIN_EMAILS.includes(email.toLowerCase()),isPremium=account?.accountType==="premium"||account?.premiumStatus==="approved"||isAdmin;$("#adminNav")?.classList.toggle("hidden",!isAdmin);$("#accountBox")?.classList.toggle("hidden",!authUser);$("#accountEmail").textContent=email;$("#accountStatus").textContent=isPremium?"Premium account":"Basic account";$("#upgradePremium")?.classList.toggle("hidden",isPremium)}
function todayKey(){return new Date().toISOString().slice(0,10)}
function isAdminEmail(email){return ADMIN_EMAILS.includes(String(email||"").toLowerCase())}
async function firestoreSyncAccount(){let db=fb.firestore(),ref=db.collection("users").doc(authUser.uid),snap=await ref.get(),admin=isAdminEmail(authUser.email),now=firebase.firestore.FieldValue.serverTimestamp();if(!snap.exists){account={uid:authUser.uid,email:authUser.email,displayName:authUser.displayName||"",accountType:admin?"premium":"basic",premiumStatus:admin?"approved":"none",lastTestDate:"",testsToday:0};await ref.set({...account,createdAt:now,lastLoginAt:now})}else{account={uid:authUser.uid,...snap.data()};account={...account,email:authUser.email,displayName:authUser.displayName||"",accountType:admin?"premium":account.accountType||"basic",premiumStatus:admin?"approved":account.premiumStatus||"none"};await ref.set({email:account.email,displayName:account.displayName,lastLoginAt:now,accountType:account.accountType,premiumStatus:account.premiumStatus},{merge:true})}return account}
async function syncAccount(){try{let res=await callFn("syncUser");account=res.user;renderAccount();showAuthMessage("")}catch(e){try{account=await firestoreSyncAccount();renderAccount();showAuthMessage("")}catch(err){showAuthMessage(err.message||"Could not sync account.")}}}
async function clearOldAppCache(){try{if("serviceWorker"in navigator){let regs=await navigator.serviceWorker.getRegistrations();await Promise.all(regs.map(reg=>reg.unregister()))}if("caches"in window){let names=await caches.keys();await Promise.all(names.map(name=>caches.delete(name)))}}catch(e){}}
async function signInProvider(){if(!fb)return;try{showAuthMessage("Opening Google sign-in...");await clearOldAppCache();let provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});let result=await firebase.auth().signInWithPopup(provider);if(result?.user)await applySignedInUser(result.user)}catch(e){showAuthMessage(e.message||"Sign-in failed.")}}
async function initFirebaseAuth(){if(!firebaseConfigured()){setAuthGate(true);showAuthMessage("Firebase is not configured yet. Paste your Firebase config into firebase-config.js first.");return}firebase.initializeApp(window.FIREBASE_CONFIG);fb=firebase;functionsApi=firebase.functions();let handleUser=async user=>{authUser=user;if(!user){account=null;renderAccount();setAuthGate(true);return}setAuthGate(false);showAuthMessage(`Signed in as ${user.email||"your account"}. Loading your plan...`);await syncAccount()};firebase.auth().getRedirectResult().then(r=>{if(r?.user)handleUser(r.user)}).catch(e=>showAuthMessage(e.message||"Google sign-in could not finish."));firebase.auth().onAuthStateChanged(handleUser);let tries=0,check=setInterval(()=>{tries++;let user=firebase.auth().currentUser;if(user){clearInterval(check);handleUser(user)}else if(tries>20){clearInterval(check)}},250)}
async function canStartPractice(){if(!authUser){setAuthGate(true);toast("Please sign in first.");return false}try{await callFn("startTestSession");return true}catch(e){try{await syncAccount();let premium=account?.accountType==="premium"||account?.premiumStatus==="approved"||isAdminEmail(authUser.email),today=todayKey();if(!premium&&account?.lastTestDate===today&&(account?.testsToday||0)>=1){toast("Basic accounts can take one test per day. You can request premium for unlimited tests.");return false}let nextCount=account?.lastTestDate===today?(account?.testsToday||0)+1:1;await fb.firestore().collection("users").doc(authUser.uid).set({lastTestDate:today,testsToday:nextCount},{merge:true});account.lastTestDate=today;account.testsToday=nextCount;return true}catch(err){toast(err.message||"Could not check your account yet.");return false}}}
async function requestPremium(){try{let res=await callFn("requestPremium");toast(res.status==="already-premium"?"You are already premium.":"Premium request sent to admin.");await syncAccount()}catch(e){try{if(!authUser)return;await fb.firestore().collection("premiumRequests").doc(authUser.uid).set({uid:authUser.uid,email:authUser.email,displayName:authUser.displayName||"",status:"pending",createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await fb.firestore().collection("users").doc(authUser.uid).set({premiumStatus:"requested"},{merge:true});toast("Premium request sent to admin.");await syncAccount()}catch(err){toast(err.message||"Could not request premium.")}}}
function countUsage(items,ms){let since=Date.now()-ms;return items.filter(x=>x.createdAt?.seconds*1000>=since).length}
async function renderAdmin(){try{let data=await callFn("adminListDashboard"),usage=data.usage||[],users=data.users||[],requests=data.premiumRequests||[];$("#adminStats").innerHTML=stats([["Users",users.length],["Premium requests",requests.length],["Usage 24h",countUsage(usage,86400000)],["Usage 30d",countUsage(usage,2592000000)]]);$("#premiumRequests").innerHTML=requests.length?requests.map(r=>`<div class="history-row"><strong>${escapeHtml(r.email)}</strong><span>${escapeHtml(r.displayName||"")}</span><button class="soft" data-approve="${escapeHtml(r.uid)}">Approve</button></div>`).join(""):`<p class="fine-print">No pending requests.</p>`;$("#adminUsers").innerHTML=users.map(u=>`<div class="history-row"><strong>${escapeHtml(u.email||"")}</strong><span>${escapeHtml(u.accountType||"basic")} · ${escapeHtml(u.premiumStatus||"none")}</span><span>${u.lastLoginAt?.seconds?new Date(u.lastLoginAt.seconds*1000).toLocaleDateString():""}</span></div>`).join("");$$("[data-approve]").forEach(b=>b.onclick=async()=>{await callFn("adminSetPremium",{uid:b.dataset.approve,approved:true});toast("Premium approved.");renderAdmin()})}catch(e){$("#premiumRequests").innerHTML=`<p class="fine-print">${escapeHtml(e.message||"Admin data unavailable.")}</p>`}}
async function renderAdmin(){try{let data=await callFn("adminListDashboard"),usage=data.usage||[],users=data.users||[],requests=data.premiumRequests||[];renderAdminLists(users,requests,usage,async uid=>callFn("adminSetPremium",{uid,approved:true}))}catch(e){try{if(!isAdminEmail(authUser?.email))throw new Error("Admin only.");let db=fb.firestore(),usersSnap=await db.collection("users").get(),reqSnap=await db.collection("premiumRequests").get(),users=usersSnap.docs.map(d=>({uid:d.id,...d.data()})),requests=reqSnap.docs.map(d=>({uid:d.id,...d.data()}));renderAdminLists(users,requests,[],async uid=>{await db.collection("users").doc(uid).set({accountType:"premium",premiumStatus:"approved"},{merge:true});await db.collection("premiumRequests").doc(uid).delete()})}catch(err){$("#premiumRequests").innerHTML=`<p class="fine-print">${escapeHtml(err.message||"Admin data unavailable.")}</p>`}}}
function renderAdminLists(users,requests,usage,approve){$("#adminStats").innerHTML=stats([["Users",users.length],["Premium requests",requests.length],["Usage 24h",countUsage(usage,86400000)],["Usage 30d",countUsage(usage,2592000000)]]);$("#premiumRequests").innerHTML=requests.length?requests.map(r=>`<div class="history-row"><strong>${escapeHtml(r.email)}</strong><span>${escapeHtml(r.displayName||"")}</span><button class="soft" data-approve="${escapeHtml(r.uid)}">Approve</button></div>`).join(""):`<p class="fine-print">No pending requests.</p>`;$("#adminUsers").innerHTML=users.map(u=>`<div class="history-row"><strong>${escapeHtml(u.email||"")}</strong><span>${escapeHtml(u.accountType||"basic")} · ${escapeHtml(u.premiumStatus||"none")}</span><span>${u.lastLoginAt?.seconds?new Date(u.lastLoginAt.seconds*1000).toLocaleDateString():""}</span></div>`).join("");$$("[data-approve]").forEach(b=>b.onclick=async()=>{await approve(b.dataset.approve);toast("Premium approved.");renderAdmin()})}
async function syncAccount(){try{account=await firestoreSyncAccount();renderAccount();showAuthMessage("")}catch(err){showAuthMessage(err.message||"Could not sync account.")}}
async function canStartPractice(){if(!authUser){setAuthGate(true);toast("Please sign in first.");return false}try{await syncAccount();let premium=account?.accountType==="premium"||account?.premiumStatus==="approved"||isAdminEmail(authUser.email),today=todayKey();if(!premium&&account?.lastTestDate===today&&(account?.testsToday||0)>=1){toast("Basic accounts can take one test per day. You can request premium for unlimited tests.");return false}let nextCount=account?.lastTestDate===today?(account?.testsToday||0)+1:1;await fb.firestore().collection("users").doc(authUser.uid).set({lastTestDate:today,testsToday:nextCount},{merge:true});account.lastTestDate=today;account.testsToday=nextCount;return true}catch(err){toast(err.message||"Could not check your account yet.");return false}}
async function requestPremium(){try{if(!authUser)return;await fb.firestore().collection("premiumRequests").doc(authUser.uid).set({uid:authUser.uid,email:authUser.email,displayName:authUser.displayName||"",status:"pending",createdAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await fb.firestore().collection("users").doc(authUser.uid).set({premiumStatus:"requested"},{merge:true});toast("Premium request sent to admin.");await syncAccount()}catch(err){toast(err.message||"Could not request premium.")}}
async function renderAdmin(){try{if(!isAdminEmail(authUser?.email))throw new Error("Admin only.");let db=fb.firestore(),usersSnap=await db.collection("users").get(),reqSnap=await db.collection("premiumRequests").get(),users=usersSnap.docs.map(d=>({uid:d.id,...d.data()})),requests=reqSnap.docs.map(d=>({uid:d.id,...d.data()}));renderAdminLists(users,requests,[],async uid=>{await db.collection("users").doc(uid).set({accountType:"premium",premiumStatus:"approved"},{merge:true});await db.collection("premiumRequests").doc(uid).delete()})}catch(err){$("#premiumRequests").innerHTML=`<p class="fine-print">${escapeHtml(err.message||"Admin data unavailable.")}</p>`}}
function renderAdminLists(users,requests,usage,approve){let pending=[...requests],pendingIds=new Set(pending.map(r=>r.uid||r.id));users.forEach(u=>{let uid=u.uid||u.id;if(uid&&!pendingIds.has(uid)&&u.premiumStatus==="requested"&&u.accountType!=="premium"){pending.push({...u,uid,status:"requested"});pendingIds.add(uid)}});$("#adminStats").innerHTML=stats([["Users",users.length],["Premium requests",pending.length],["Usage 24h",countUsage(usage,86400000)],["Usage 30d",countUsage(usage,2592000000)]]);$("#premiumRequests").innerHTML=pending.length?pending.map(r=>`<div class="history-row"><strong>${escapeHtml(r.email||"")}</strong><span>${escapeHtml(r.displayName||r.status||"requested")}</span><button class="soft" data-approve="${escapeHtml(r.uid||r.id)}">Approve</button></div>`).join(""):`<p class="fine-print">No pending requests.</p>`;$("#adminUsers").innerHTML=users.map(u=>{let uid=u.uid||u.id,needsApproval=u.premiumStatus==="requested"&&u.accountType!=="premium";return`<div class="history-row"><strong>${escapeHtml(u.email||"")}</strong><span>${escapeHtml(u.accountType||"basic")} · ${escapeHtml(u.premiumStatus||"none")}</span>${needsApproval?`<button class="soft" data-approve="${escapeHtml(uid)}">Approve</button>`:`<span>${u.lastLoginAt?.seconds?new Date(u.lastLoginAt.seconds*1000).toLocaleDateString():""}</span>`}</div>`}).join("");$$("[data-approve]").forEach(b=>b.onclick=async()=>{await approve(b.dataset.approve);toast("Premium approved.");renderAdmin()})}
function applyProfile(){let p=data.profile;document.documentElement.dataset.theme=p.theme||"lavender";$("#studentName").value=p.name||"";$("#voiceMode").value=p.voice||"bestie";$("#planLength").value=p.plan||"4";$("#themeSelect").value=p.theme||"lavender";$("#examMode").value=p.examMode||"adaptive";$("#topicSelect").value=p.topic||"Functions";$("#topicDifficulty").value=p.topicDifficulty||"Warm-up";$("#topicQuestionCount").value=p.topicQuestionCount||"10";$("#topicTestMinutes").value=p.topicTestMinutes||"30";updateSetupMode()}
function getFocus(){if(!data.history.length)return"Diagnostic mix";let t=data.history[0].topics||{};return Object.entries(t).sort((a,b)=>a[1].percent-b[1].percent)[0]?.[0]||"Mixed review"}
function allTopics(){return [...new Set(QUESTIONS.map(q=>q.topic))]}
function chooseQuestions(){data=shapeData(data);let topics=allTopics(),weak=getFocus(),focus=topics.includes(weak)?weak:topics[data.generatorLog.sessionCounter%topics.length],levels=["Warm-up","Easy","Medium","Honors"],questions=[];questions.push(...chooseTopicQuestions(focus,3,levels[data.generatorLog.sessionCounter%levels.length],{remember:false}));for(let i=0;questions.length<10&&i<topics.length*2;i++){let topic=topics[(i+data.generatorLog.sessionCounter)%topics.length];questions.push(...chooseTopicQuestions(topic,1,levels[i%levels.length],{remember:false}))}let unique=[],seen=new Set();questions.forEach(q=>{let key=questionKey(q);if(!seen.has(key)&&unique.length<10){seen.add(key);unique.push(q)}});rememberQuestionSet(unique);return unique}
function gcd(a,b){while(b)[a,b]=[b,a%b];return Math.abs(a)}
function generatedTopicQuestion(topic,i,difficulty){
  const level=difficulty||["Warm-up","Easy","Medium","Honors"][[0,1,2,3][Math.min(3,Math.floor(i%8/2))]],boost={ "Warm-up":0, Easy:1, Medium:2, Honors:3 }[level]||0;
  i=i+boost*7;
  const n=i+1,id=`generated-${topic}-${Date.now()}-${i}`,base={id,topic,difficulty:level,type:"text"};
  const sign=v=>v<0?`- ${Math.abs(v)}`:`+ ${v}`;
  if(topic==="Functions"){
    let a=2+i%7,b=((Math.floor(i/7)+i*2)%13)-6,x=1+((Math.floor(i/91)+i*3)%9),answer=a*x+b;
    if(level==="Honors"){answer=a*x*x+b;return{...base,prompt:`If f(x) = ${a}x^2 ${sign(b)}, find f(${x}).`,answer:[String(answer),`f(${x})=${answer}`],lesson:"Substitute the input for x, square it first, then multiply and add.",explanation:`f(${x})=${a}(${x})^2 ${sign(b)}=${answer}.`,mistake:"Substitution error"}}
    if(i%3===1){answer=a*(x+b);return{...base,prompt:`If f(x) = ${a}(x ${sign(b)}), find f(${x}).`,answer:[String(answer),`f(${x})=${answer}`],lesson:"Function notation means substitute the input for x, then simplify what is inside parentheses first.",explanation:`f(${x})=${a}(${x} ${sign(b)})=${answer}.`,mistake:"Substitution error"}}
    return{...base,prompt:`If f(x) = ${a}x ${sign(b)}, find f(${x}).`,answer:[String(answer),`f(${x})=${answer}`],lesson:"Function notation means substitute the given input for x, then simplify using order of operations.",explanation:`Substitute ${x}: ${a}(${x}) ${sign(b)} = ${answer}.`,mistake:"Substitution error"};
  }
  if(topic==="Quadratics"){
    let r1=1+i%12,r2=-(1+((Math.floor(i/12)*5+i*7)%12)),sum=r1+r2,product=r1*r2,mid=-sum;
    return{...base,prompt:`Solve x^2 ${sign(mid)}x ${sign(product)} = 0. Give both solutions.`,answer:[`${r1},${r2}`,`${r2},${r1}`,`x=${r1},x=${r2}`,`x=${r2},x=${r1}`],lesson:"Factor the quadratic, then set each factor equal to zero.",explanation:`It factors as (x-${r1})(x${r2<0?"+":"-"}${Math.abs(r2)}), so x=${r1} or x=${r2}.`,mistake:"Factoring error"};
  }
  if(topic==="Complex Numbers"){
    let exponent=5+(i*7)%120,cycle=["1","i","-1","-i"],answer=cycle[exponent%4],form=Math.floor(i/120)%3;
    if(form===1)return{...base,type:"mc",prompt:`Find the value of i^${exponent}.`,choices:["1","-1","i","-i"],answer,lesson:"Powers of i repeat every four: 1, i, -1, -i. Use the exponent's remainder after division by 4.",explanation:`${exponent} has remainder ${exponent%4} when divided by 4, so the value is ${answer}.`,mistake:"Power cycle error"};
    if(form===2)return{...base,type:"mc",prompt:`Simplify the imaginary number power i^${exponent}.`,choices:["1","-1","i","-i"],answer,lesson:"Powers of i repeat every four: 1, i, -1, -i. Use the exponent's remainder after division by 4.",explanation:`${exponent} has remainder ${exponent%4} when divided by 4, so the value is ${answer}.`,mistake:"Power cycle error"};
    return{...base,type:"mc",prompt:`Simplify i^${exponent}.`,choices:["1","-1","i","-i"],answer,lesson:"Powers of i repeat every four: 1, i, -1, -i. Use the exponent's remainder after division by 4.",explanation:`${exponent} has remainder ${exponent%4} when divided by 4, so the value is ${answer}.`,mistake:"Power cycle error"};
  }
  if(topic==="Polynomials"){
    let a=1+i%9,b=((Math.floor(i/9)*2+i*3)%11)-5,c=1+(Math.floor(i/99)+i)%9,answer=a*a+b*a+c;
    return{...base,prompt:`Find the remainder when p(x)=x^2 ${sign(b)}x + ${c} is divided by x-${a}.`,answer:[String(answer)],lesson:"The Remainder Theorem says the remainder after dividing p(x) by x-a is p(a).",explanation:`p(${a})=${a}^2 ${sign(b)}(${a})+${c}=${answer}.`,mistake:"Remainder Theorem error"};
  }
  if(topic==="Rational Functions"){
    let a=2+i%13,b=1+((Math.floor(i/13)+i*3)%9),form=Math.floor(i/117)%4;
    if(form===1)return{...base,type:"mc",prompt:`Simplify (x^2-${a*a})/(x+${a}), where x cannot equal -${a}.`,choices:[`x-${a}`,`x+${a}`,`x^2+${a}`,"1"],answer:`x-${a}`,lesson:"Factor a difference of squares: x^2-a^2=(x-a)(x+a), then cancel the common factor while keeping the restriction.",explanation:`x^2-${a*a}=(x-${a})(x+${a}), so the simplified expression is x-${a}.`,mistake:"Factoring or restriction error"};
    if(form===2)return{...base,type:"mc",prompt:`Simplify ((x-${a})(x+${b}))/(x-${a}), where x cannot equal ${a}.`,choices:[`x+${b}`,`x-${a}`,`x+${a}`,"1"],answer:`x+${b}`,lesson:"Cancel only common factors, not random terms. Keep the value that made the canceled factor zero as a restriction.",explanation:`The factor x-${a} cancels, leaving x+${b}.`,mistake:"Factoring or restriction error"};
    if(form===3)return{...base,type:"mc",prompt:`After simplifying ((x+${a})(x-${b}))/(x+${a}), what expression remains?`,choices:[`x-${b}`,`x+${a}`,`x+${b}`,"1"],answer:`x-${b}`,lesson:"Cancel only common factors, not random terms.",explanation:`The factor x+${a} cancels, leaving x-${b}.`,mistake:"Factoring or restriction error"};
    return{...base,type:"mc",prompt:`Simplify (x^2-${a*a})/(x-${a}), where x cannot equal ${a}.`,choices:[`x-${a}`,`x+${a}`,`x^2+${a}`,"1"],answer:`x+${a}`,lesson:"Factor a difference of squares: x^2-a^2=(x-a)(x+a), then cancel the common factor while keeping the restriction.",explanation:`x^2-${a*a}=(x-${a})(x+${a}), so the simplified expression is x+${a}.`,mistake:"Factoring or restriction error"};
  }
  if(topic==="Radicals"){
    let squareFree=[2,3,5,6,7,10,11,13,14,15,17,19][(i*5)%12],coefficient=2+(i%9),radicand=coefficient*coefficient*squareFree,form=Math.floor(i/12)%4,outside=1+(Math.floor(i/48)%4);
    if(level==="Easy"){squareFree=[2,3,5,6,7][i%5];coefficient=2+(Math.floor(i/5)%5);radicand=coefficient*coefficient*squareFree;form=Math.floor(i/25)%2;outside=1}
    if(form===1)return{...base,prompt:`Write sqrt(${radicand}) in simplest radical form.`,answer:[`${coefficient}sqrt(${squareFree})`,`${coefficient}sqrt${squareFree}`],lesson:"Find the largest perfect-square factor, take its square root outside, and leave the square-free factor inside.",explanation:`${radicand}=${coefficient*coefficient}*${squareFree}, so sqrt(${radicand})=${coefficient}sqrt(${squareFree}).`,mistake:"Radical simplification"};
    if(form===2)return{...base,prompt:`Simplify ${outside}sqrt(${radicand}).`,answer:[`${outside*coefficient}sqrt(${squareFree})`,`${outside*coefficient}sqrt${squareFree}`],lesson:"Simplify the radical first, then multiply by the number outside.",explanation:`sqrt(${radicand})=${coefficient}sqrt(${squareFree}), then ${outside}*${coefficient}=${outside*coefficient}.`,mistake:"Radical simplification"};
    if(form===3)return{...base,prompt:`Simplify sqrt(${outside*outside*radicand})/${outside}.`,answer:[`${coefficient}sqrt(${squareFree})`,`${coefficient}sqrt${squareFree}`],lesson:"Simplify the square root first, then divide by the outside number.",explanation:`sqrt(${outside*outside*radicand})=${outside*coefficient}sqrt(${squareFree}), and dividing by ${outside} leaves ${coefficient}sqrt(${squareFree}).`,mistake:"Radical simplification"};
    return{...base,prompt:`Simplify sqrt(${radicand}).`,answer:[`${coefficient}sqrt(${squareFree})`,`${coefficient}sqrt${squareFree}`],lesson:"Find the largest perfect-square factor, take its square root outside, and leave the square-free factor inside.",explanation:`${radicand}=${coefficient*coefficient}*${squareFree}, so sqrt(${radicand})=${coefficient}sqrt(${squareFree}).`,mistake:"Radical simplification"};
  }
  if(topic==="Exponential Functions"){
    let bases=[2,3,4,5],baseNum=bases[i%bases.length],exponent=2+(Math.floor(i/4)%4),value=baseNum**exponent,coef=2+(Math.floor(i/64)+i)%4,shift=1+(Math.floor(i/16)%3),form=Math.floor(i/48)%4;
    if(form===1)return{...base,prompt:`Solve ${coef}*${baseNum}^x = ${coef*value}.`,answer:[String(exponent),`x=${exponent}`],lesson:"First divide away the coefficient, then match powers with the same base.",explanation:`Divide by ${coef}: ${baseNum}^x=${value}. Since ${baseNum}^${exponent}=${value}, x=${exponent}.`,mistake:"Exponent rule error"};
    if(form===2)return{...base,prompt:`Solve ${baseNum}^(x+${shift}) = ${baseNum**(exponent+shift)}.`,answer:[String(exponent),`x=${exponent}`],lesson:"When the bases match, set the exponents equal and solve the small equation.",explanation:`x+${shift}=${exponent+shift}, so x=${exponent}.`,mistake:"Exponent equation error"};
    if(form===3)return{...base,prompt:`Solve ${baseNum}^(x-${shift}) = ${baseNum**exponent}.`,answer:[String(exponent+shift),`x=${exponent+shift}`],lesson:"When the bases match, set the exponents equal and solve the small equation.",explanation:`x-${shift}=${exponent}, so x=${exponent+shift}.`,mistake:"Exponent equation error"};
    return{...base,prompt:`Solve ${baseNum}^x = ${value}.`,answer:[String(exponent),`x=${exponent}`],lesson:"This is exponential because x is in the exponent. Write both sides with the same base, then set the exponents equal.",explanation:`${value}=${baseNum}^${exponent}, so x=${exponent}.`,mistake:"Exponent rule error"};
  }
  if(topic==="Logarithms"){
    let bases=[2,3,4,5],baseNum=bases[i%bases.length],exponent=2+(Math.floor(i/4)%4),value=baseNum**exponent,form=Math.floor(i/16)%8;
    if(level==="Warm-up"){baseNum=bases[i%bases.length];exponent=2+(Math.floor(i/4)%4);value=baseNum**exponent}
    if(form===1)return{...base,prompt:`Solve log base ${baseNum} of x = ${exponent}.`,answer:[String(value),`x=${value}`],lesson:"A log is asking for an exponent. If log base a of b = c, then a^c=b.",explanation:`${baseNum}^${exponent}=${value}, so x=${value}.`,mistake:"Logarithm meaning error"};
    if(form===2)return{...base,type:"mc",prompt:`Which equation matches log base ${baseNum} of ${value} = ${exponent}?`,choices:[`${baseNum}^${exponent}=${value}`,`${exponent}^${baseNum}=${value}`,`${value}^${baseNum}=${exponent}`,`${baseNum}^${value}=${exponent}`],answer:`${baseNum}^${exponent}=${value}`,lesson:"log base a of b = c means a^c=b.",explanation:`The base is ${baseNum}, the exponent is ${exponent}, and the result is ${value}.`,mistake:"Log form confusion"};
    if(form===3)return{...base,prompt:`Evaluate log base ${baseNum} of ${value*baseNum}, then subtract 1.`,answer:[String(exponent),`${exponent}`],lesson:"A logarithm asks what exponent makes the base reach the number.",explanation:`${value*baseNum}=${baseNum}^${exponent+1}, so the power is ${exponent+1}. Then ${exponent+1}-1=${exponent}.`,mistake:"Logarithm meaning error"};
    if(form===4)return{...base,prompt:`Rewrite ${baseNum}^${exponent} = ${value} in logarithmic form.`,answer:[`log_${baseNum}(${value})=${exponent}`,`log base ${baseNum} of ${value} = ${exponent}`],lesson:"Exponential form a^c=b matches logarithmic form log base a of b = c.",explanation:`The base is ${baseNum}, the result is ${value}, and the exponent is ${exponent}, so log base ${baseNum} of ${value} = ${exponent}.`,mistake:"Log form confusion"};
    if(form===5)return{...base,prompt:`Solve log base ${baseNum} of ${value} = x.`,answer:[String(exponent),`x=${exponent}`],lesson:"A logarithm asks what exponent is needed.",explanation:`${baseNum}^${exponent}=${value}, so x=${exponent}.`,mistake:"Logarithm meaning error"};
    if(form===6)return{...base,prompt:`What exponent makes ${baseNum}^x = ${value}? Write the log value.`,answer:[String(exponent),`log_${baseNum}(${value})=${exponent}`],lesson:"This is the same idea as log base a of b: find the exponent.",explanation:`${baseNum}^${exponent}=${value}, so the log value is ${exponent}.`,mistake:"Logarithm meaning error"};
    if(form===7)return{...base,prompt:`Evaluate log base ${baseNum} of ${value/baseNum}, then add 1.`,answer:[String(exponent),`${exponent}`],lesson:"Use the power that matches the number inside the log, then follow the extra operation.",explanation:`${value/baseNum}=${baseNum}^${exponent-1}, so the log is ${exponent-1}. Then ${exponent-1}+1=${exponent}.`,mistake:"Logarithm meaning error"};
    return{...base,prompt:`What is log base ${baseNum} of ${value}? Translation: ${baseNum} to what power equals ${value}?`,answer:[String(exponent),`log_${baseNum}(${value})=${exponent}`],lesson:"A logarithm asks what exponent is needed. log base a of b means: a to what power equals b?",explanation:`${baseNum}^${exponent}=${value}, so the answer is ${exponent}.`,mistake:"Logarithm meaning error"};
  }
  if(topic==="Sequences"){
    let first=1+(i*2)%8,difference=2+i%5,term=4+(i*3)%7,answer=first+(term-1)*difference;
    return{...base,prompt:`Find term ${term} of the arithmetic sequence with a1=${first} and common difference d=${difference}.`,answer:[String(answer),`a${term}=${answer}`],lesson:"Use a_n=a1+(n-1)d for an arithmetic sequence.",explanation:`a${term}=${first}+(${term}-1)(${difference})=${answer}.`,mistake:"Sequence formula error"};
  }
  if(topic==="Systems"){
    let x=1+i%8,y=2+(Math.floor(i/8)+i*3)%9,m1=1+(Math.floor(i/72)+i)%3,m2=-(1+((Math.floor(i/24)+i)%3)),b1=y-m1*x,b2=y-m2*x;
    return{...base,prompt:`Solve the system y=${m1}x ${sign(b1)} and y=${m2}x ${sign(b2)}. Give the ordered pair.`,answer:[`(${x},${y})`,`${x},${y}`],lesson:"Set the two expressions for y equal, solve for x, and substitute to find y.",explanation:`The two equations are equal at x=${x}; substituting gives y=${y}. The solution is (${x}, ${y}).`,mistake:"System solving error"};
  }
  if(topic==="Trigonometry"){
    let raw=15*(1+(i%47)),degrees=raw,common=gcd(Math.abs(degrees),180),num=degrees/common,den=180/common,answer=den===1?`${num===1?"":num}pi`:`${num===1?"":num}pi/${den}`,form=Math.floor(i/47)%3;
    if(form===1)return{...base,prompt:`Convert -${raw} degrees to radians.`,answer:[answer.startsWith("-")?answer:`-${answer}`],lesson:"Multiply degrees by pi/180, then reduce the fraction. Keep the negative sign if the angle is negative.",explanation:`-${raw}*pi/180 simplifies to ${answer.startsWith("-")?answer:`-${answer}`}.`,mistake:"Degree/radian conversion"};
    if(form===2)return{...base,prompt:`Convert ${raw+360} degrees to radians.`,answer:[`${(raw+360)/gcd(raw+360,180)===1?"":(raw+360)/gcd(raw+360,180)}pi/${180/gcd(raw+360,180)}`.replace("/1","")],lesson:"Multiply degrees by pi/180, then reduce the fraction.",explanation:`${raw+360}*pi/180 simplifies after reducing the fraction.`,mistake:"Degree/radian conversion"};
    return{...base,prompt:`Convert ${degrees} degrees to radians.`,answer:[answer],lesson:"Multiply degrees by pi/180, then reduce the fraction.",explanation:`${degrees}*pi/180 simplifies to ${answer}.`,mistake:"Degree/radian conversion"};
  }
  if(topic==="Functions"){
    let a=2+i%4,b=(i%7)-3,x=1+i%6,answer=a*x+b;
    return{...base,prompt:`If f(x) = ${a}x ${b<0?"−":"+"} ${Math.abs(b)}, find f(${x}).`,answer:[String(answer),`f(${x})=${answer}`],lesson:"Function notation means substitute the given input for x, then simplify using order of operations.",explanation:`Substitute ${x}: ${a}(${x}) ${b<0?"−":"+"} ${Math.abs(b)} = ${answer}.`,mistake:"Substitution error"};
  }
  if(topic==="Quadratics"){
    let r1=1+i%5,r2=-(1+(i*2)%5),sum=r1+r2,product=r1*r2,mid=-sum;
    return{...base,prompt:`Solve x² ${mid<0?"−":"+"} ${Math.abs(mid)}x ${product<0?"−":"+"} ${Math.abs(product)} = 0. Give both solutions.`,answer:[`${r1},${r2}`,`${r2},${r1}`,`x=${r1},x=${r2}`,`x=${r2},x=${r1}`],lesson:"Factor the quadratic into (x−r₁)(x−r₂), then set each factor equal to zero.",explanation:`It factors as (x−${r1})(x${r2<0?"+":"−"}${Math.abs(r2)}), so x=${r1} or x=${r2}.`,mistake:"Factoring error"};
  }
  if(topic==="Complex Numbers"){
    let exponent=7+i*3,cycle=["1","i","−1","−i"],answer=cycle[exponent%4];
    return{...base,type:"mc",prompt:`Simplify i${String(exponent).split("").map(d=>"⁰¹²³⁴⁵⁶⁷⁸⁹"[d]).join("")}.`,choices:["1","−1","i","−i"],answer,lesson:"Powers of i repeat every four: 1, i, −1, −i. Use the exponent's remainder after division by 4.",explanation:`${exponent} has remainder ${exponent%4} when divided by 4, so the value is ${answer}.`,mistake:"Power cycle error"};
  }
  if(topic==="Polynomials"){
    let a=1+i%5,b=(i%7)-3,c=1+i%5,answer=a*a+b*a+c;
    return{...base,prompt:`Find the remainder when p(x)=x² ${b<0?"−":"+"} ${Math.abs(b)}x + ${c} is divided by x−${a}.`,answer:[String(answer)],lesson:"The Remainder Theorem says the remainder after dividing p(x) by x−a is p(a).",explanation:`p(${a})=${a}² ${b<0?"−":"+"} ${Math.abs(b)}(${a})+${c}=${answer}.`,mistake:"Remainder Theorem error"};
  }
  if(topic==="Rational Functions"){
    let a=2+i%7;
    return{...base,type:"mc",prompt:`Simplify (x²−${a*a})/(x−${a}), where x≠${a}.`,choices:[`x−${a}`,`x+${a}`,`x²+${a}`,"1"],answer:`x+${a}`,lesson:"Factor a difference of squares: x²−a²=(x−a)(x+a), then cancel the common factor while keeping the restriction.",explanation:`x²−${a*a}=(x−${a})(x+${a}), so the simplified expression is x+${a}.`,mistake:"Factoring or restriction error"};
  }
  if(topic==="Radicals"){
    let squareFree=[2,3,5,6,7,10][i%6],coefficient=2+i%5,radicand=coefficient*coefficient*squareFree;
    return{...base,prompt:`Simplify √${radicand}.`,answer:[`${coefficient}√${squareFree}`,`${coefficient}sqrt(${squareFree})`,`${coefficient}sqrt${squareFree}`],lesson:"Find the largest perfect-square factor, take its square root outside, and leave the square-free factor inside.",explanation:`${radicand}=${coefficient*coefficient}·${squareFree}, so √${radicand}=${coefficient}√${squareFree}.`,mistake:"Radical simplification"};
  }
  if(topic==="Exponential Functions"){
    let exponent=2+i%4,baseNum=2+i%2,value=baseNum**exponent;
    return{...base,prompt:`Solve ${baseNum}ˣ = ${value}.`,answer:[String(exponent),`x=${exponent}`],lesson:"This is exponential because x is in the exponent. Write both sides with the same base, then set the exponents equal.",explanation:`${value}=${baseNum}^${exponent}, so x=${exponent}.`,mistake:"Exponent rule error"};
  }
  if(topic==="Logarithms"){
    let exponent=2+i%4,baseNum=2+i%2,value=baseNum**exponent;
    return{...base,prompt:`What is log base ${baseNum} of ${value}? Translation: ${baseNum} to what power equals ${value}?`,answer:[String(exponent),`log_${baseNum}(${value})=${exponent}`],lesson:`A logarithm asks “what exponent?” Rewrite log base ${baseNum} of ${value}=x as ${baseNum}ˣ=${value}.`,explanation:`${baseNum}^${exponent}=${value}, so the answer is ${exponent}.`,mistake:"Logarithm meaning error"};
  }
  if(topic==="Sequences"){
    let first=1+i%6,difference=2+i%4,term=4+i%5,answer=first+(term-1)*difference;
    return{...base,prompt:`Find term ${term} of the arithmetic sequence with a₁=${first} and common difference d=${difference}.`,answer:[String(answer),`a${term}=${answer}`],lesson:"Use aₙ=a₁+(n−1)d for an arithmetic sequence.",explanation:`a${term}=${first}+(${term}−1)(${difference})=${answer}.`,mistake:"Sequence formula error"};
  }
  if(topic==="Systems"){
    let x=1+i%5,y=2+(i*2)%7,m1=1+i%2,m2=-(1+(i%2)),b1=y-m1*x,b2=y-m2*x;
    return{...base,prompt:`Solve the system y=${m1}x ${b1<0?"−":"+"} ${Math.abs(b1)} and y=${m2}x + ${b2}. Give the ordered pair.`,answer:[`(${x},${y})`,`${x},${y}`],lesson:"Set the two expressions for y equal, solve for x, and substitute to find y.",explanation:`The two equations are equal at x=${x}; substituting gives y=${y}. The solution is (${x}, ${y}).`,mistake:"System solving error"};
  }
  let degrees=[30,45,60,90,120,135,150][i%7],common=gcd(degrees,180),num=degrees/common,den=180/common,answer=den===1?`${num===1?"":num}π`:`${num===1?"":num}π/${den}`;
  return{...base,prompt:`Convert ${degrees}° to radians.`,answer:[answer,`${num===1?"":num}pi/${den}`,den===1?`${num}pi`:answer],lesson:"Multiply degrees by π/180, then reduce the fraction.",explanation:`${degrees}·π/180 simplifies to ${answer}.`,mistake:"Degree/radian conversion"};
}
function cleanGeneratedQuestion(topic,q,seed){if(topic==="Exponential Functions"&&/log/i.test(`${q.prompt} ${q.lesson} ${q.explanation}`)){q=generatedTopicQuestion(topic,seed+41,q.difficulty)}q.id=`${q.id}-${Math.floor(Math.random()*100000)}`;return q}
function chooseTopicQuestions(topic,count,difficulty,options={}){data=shapeData(data);let remember=options.remember!==false,used=new Set(data.generatorLog.usedPromptKeys),picked=[],pickedKeys=new Set(),seed=(++data.generatorLog.sessionCounter*97)+(Date.now()%997)+Math.floor(Math.random()*997),limit=Math.max(2400,count*220);for(let tries=0;picked.length<count&&tries<limit;tries++){let q=cleanGeneratedQuestion(topic,generatedTopicQuestion(topic,seed+tries*3,difficulty),seed+tries*3),key=questionKey(q);if(!pickedKeys.has(key)&&!used.has(key)){picked.push(q);pickedKeys.add(key)}}for(let tries=0;picked.length<count&&tries<limit;tries++){let q=cleanGeneratedQuestion(topic,generatedTopicQuestion(topic,seed+tries*5+13,difficulty),seed+tries*5+13),key=questionKey(q);if(!pickedKeys.has(key)){picked.push(q);pickedKeys.add(key)}}for(let tries=0;picked.length<count&&tries<limit;tries++){let q=cleanGeneratedQuestion(topic,generatedTopicQuestion(topic,seed+tries*11+503,difficulty),seed+tries*11+503),key=questionKey(q);if(!pickedKeys.has(key)){picked.push(q);pickedKeys.add(key)}}while(picked.length<count){let q=cleanGeneratedQuestion(topic,generatedTopicQuestion(topic,seed+picked.length*17+5003,difficulty),seed+picked.length*17+5003);picked.push(q)}if(remember)rememberQuestionSet(picked);return picked}
function chooseUnitQuestions(topic,count){let levels=["Warm-up","Easy","Medium","Honors"],picked=[],seen=new Set(),tries=0;while(picked.length<count&&tries<count*60+240){let level=levels[tries%levels.length],q=chooseTopicQuestions(topic,1,level,{remember:false})[0],key=questionKey(q);if(!seen.has(key)){picked.push(q);seen.add(key)}tries++}while(picked.length<count){let level=levels[picked.length%levels.length],q=chooseTopicQuestions(topic,1,level,{remember:false})[0];picked.push(q)}rememberQuestionSet(picked);return picked}
function validPositiveInteger(value){return Number.isInteger(Number(value))&&Number(value)>0}
function updateSetupMode(){let mode=$("#examMode").value,customMode=mode!=="adaptive",unitMode=mode==="unit",day=data.history.length+1,count=customMode?$("#topicQuestionCount").value:10,minutes=customMode?$("#topicTestMinutes").value:30,difficulty=$("#topicDifficulty").value||"Warm-up",focus=mode==="topic"?`${$("#topicSelect").value} • ${difficulty}`:unitMode?`${$("#topicSelect").value} • mixed end-of-unit review`:getFocus();$("#topicControls").classList.toggle("hidden",!customMode);$("#topicDifficultyField")?.classList.toggle("hidden",unitMode);$("#focusLabel").textContent=mode==="topic"?"Selected topic":unitMode?"End-of-unit test":"Today’s adaptive focus";$("#todayFocus").textContent=focus;$("#dayLabel").textContent=`Day ${day} • ${count||"—"} questions • ${minutes||"—"} minutes`}
async function startExam(e){e?.preventDefault();let mode=$("#examMode").value,customMode=mode!=="adaptive",topic=$("#topicSelect").value,difficulty=$("#topicDifficulty").value,count=customMode?Number($("#topicQuestionCount").value):10,minutes=customMode?Number($("#topicTestMinutes").value):30;if(customMode&&(!validPositiveInteger(count)||!validPositiveInteger(minutes))){toast("Enter positive whole numbers for questions and minutes.");return}if(!(await canStartPractice()))return;data.profile={name:$("#studentName").value.trim(),voice:$("#voiceMode").value,plan:$("#planLength").value,theme:$("#themeSelect").value,examMode:mode,topic,topicDifficulty:difficulty,topicQuestionCount:String(count),topicTestMinutes:String(minutes)};let questions=mode==="topic"?chooseTopicQuestions(topic,count,difficulty):mode==="unit"?chooseUnitQuestions(topic,count):chooseQuestions();exam={generatorVersion:GENERATOR_VERSION,mode,selectedTopic:customMode?topic:null,selectedDifficulty:mode==="topic"?difficulty:mode==="unit"?"Mixed unit review":null,questionCount:count,timeLimitMinutes:minutes,questions,answers:{},hints:{},assisted:{},chats:{},index:0,seconds:minutes*60,totalSeconds:minutes*60,startedAt:new Date().toISOString(),formulaOpens:0};data.draft=exam;save();applyProfile();showView("exam");$("#examStudent").textContent=data.profile.voice==="bestie"?`${data.profile.name}, let's cook.`:`${data.profile.name}'s exam`;renderQuestion();startTimer()}
function makeWorksheet(){let mode=$("#examMode").value,customMode=mode!=="adaptive",topic=$("#topicSelect").value,difficulty=$("#topicDifficulty").value,count=customMode?Number($("#topicQuestionCount").value):10,minutes=customMode?Number($("#topicTestMinutes").value):30;if(customMode&&(!validPositiveInteger(count)||!validPositiveInteger(minutes))){toast("Enter a positive whole number for the worksheet questions.");return}data.profile={...data.profile,name:$("#studentName").value.trim(),voice:$("#voiceMode").value,plan:$("#planLength").value,theme:$("#themeSelect").value,examMode:mode,topic,topicDifficulty:difficulty,topicQuestionCount:String(count),topicTestMinutes:String(minutes)};save();let questions=mode==="topic"?chooseTopicQuestions(topic,count,difficulty):mode==="unit"?chooseUnitQuestions(topic,count):chooseQuestions(),title=mode==="topic"?`${topic} ${difficulty} Worksheet`:mode==="unit"?`${topic} End-of-Unit Worksheet`:"Adaptive Mix Worksheet";renderWorksheet({title,mode,topic:customMode?topic:"Adaptive mix",difficulty:mode==="topic"?difficulty:mode==="unit"?"Mixed unit review":"Mixed",count:questions.length,minutes,questions});showView("worksheet")}
function answerText(q){return Array.isArray(q.answer)?q.answer[0]:q.answer}
function renderWorksheet(w){$("#worksheetPaper").innerHTML=`<div class="worksheet-head"><p class="kicker">ALGEBRA 2 GLOW-UP</p><h1>${escapeHtml(w.title)}</h1><div class="worksheet-meta"><span>Name: ____________________</span><span>Date: ____________________</span><span>${escapeHtml(w.count)} questions</span><span>Difficulty: ${escapeHtml(w.difficulty)}</span></div><p>Show your work. Circle or write your final answer clearly.</p></div><ol class="worksheet-list">${w.questions.map(q=>`<li><div class="worksheet-topic">${escapeHtml(q.topic)} • ${escapeHtml(q.difficulty)}</div><p>${escapeHtml(q.prompt)}</p>${q.type!=="text"?`<div class="worksheet-choices">${q.choices.map((c,i)=>`<span>${String.fromCharCode(65+i)}. ${escapeHtml(c)}</span>`).join("")}</div>`:""}<div class="answer-lines"><span></span><span></span></div></li>`).join("")}</ol><section class="answer-key"><h2>Answer key</h2><ol>${w.questions.map(q=>`<li>${escapeHtml(answerText(q))}</li>`).join("")}</ol></section>`}
function renderQuestion(){let q=exam.questions[exam.index],a=exam.answers[q.id];$("#questionTopic").textContent=q.topic;$("#questionDifficulty").textContent=q.difficulty;$("#questionType").textContent=q.type==="mc"?"MULTIPLE CHOICE":q.type==="tf"?"TRUE OR FALSE":"SHORT ANSWER";$("#questionPrompt").textContent=q.prompt;let area=$("#answerArea");if(q.type==="text")area.innerHTML=`<label><span class="kicker">YOUR ANSWER</span><input class="answer-input" id="textAnswer" value="${escapeHtml(a||"")}" placeholder="Type your answer here"></label>`;else area.innerHTML=`<div class="choice-list">${q.choices.map((c,i)=>`<label class="choice"><input type="radio" name="answer" value="${escapeHtml(c)}" ${a===c?"checked":""}><span><b>${String.fromCharCode(65+i)}.</b> ${c}</span></label>`).join("")}</div>`;$("#lesson").classList.add("hidden");$("#teachButton").textContent=data.profile.voice==="bestie"?"✦ Help bestie, teach me this":"✦ Teach me this topic";$("#progressText").textContent=`${exam.index+1} / ${exam.questions.length}`;$("#progressFill").style.width=`${(exam.index+1)/exam.questions.length*100}%`;$("#prevButton").disabled=exam.index===0;$("#nextButton").textContent=exam.index===exam.questions.length-1?"Submit exam →":"Next question →";$("#questionGrid").innerHTML=exam.questions.map((x,i)=>`<button class="${i===exam.index?"current":exam.answers[x.id]!=null?"answered":""}" data-index="${i}">${i+1}</button>`).join("");$("#questionGrid").querySelectorAll("button").forEach(b=>b.onclick=()=>{exam.index=+b.dataset.index;renderQuestion()});area.querySelectorAll("input").forEach(i=>i.oninput=()=>setAnswer(q.id,i.value))}
function setAnswer(id,val){exam.answers[id]=val;data.draft=exam;save();$("#saveStatus").textContent="Saved ✓";setTimeout(()=>$("#saveStatus").textContent="Answer saves automatically",900)}
function next(){let q=exam.questions[exam.index];if(exam.answers[q.id]==null||exam.answers[q.id]===""){toast("Add an answer before moving on.");return}if(exam.index<exam.questions.length-1){exam.index++;renderQuestion()}else finishExam()}
const COACH_EXAMPLES={
  "Functions":"Example: if f(x)=2x+3, then f(4)=2(4)+3=11. Replace x with the input first.",
  "Quadratics":"Example: x²−5x+6 factors into (x−2)(x−3), so the solutions are 2 and 3.",
  "Complex Numbers":"Example: i⁶ has remainder 2 when divided by 4, so i⁶=i²=−1.",
  "Polynomials":"Example: the remainder of p(x)=x²+1 divided by x−3 is p(3)=10.",
  "Rational Functions":"Example: (x²−9)/(x−3)=(x−3)(x+3)/(x−3)=x+3, but x still cannot equal 3.",
  "Radicals":"Example: √50=√(25·2)=5√2. Pull the square root of the perfect square outside.",
  "Exponential Functions":"Example: 2ˣ=16 becomes 2ˣ=2⁴, so x=4.",
  "Logarithms":"Example: log₂(8)=3 because 2³=8. A log is asking for an exponent.",
  "Exponentials & Logs":"Example: log₂(8)=3 means 2³=8.",
  "Sequences":"Example: for 2,5,8,… the difference is 3, so a₆=2+5(3)=17.",
  "Systems":"Example: set y=x+2 and y=−x+6 equal: x+2=−x+6, so x=2 and y=4.",
  "Trigonometry":"Example: 60°·π/180=π/3 radians."
};
const COACH_FORMULAS={
  "Functions":"For f(a), replace every x in the rule with a.",
  "Quadratics":"Quadratic formula: x=(−b±√(b²−4ac))/(2a). Factoring may be faster when the numbers are friendly.",
  "Complex Numbers":"Powers of i repeat every four: i, −1, −i, 1.",
  "Polynomials":"Remainder Theorem: dividing p(x) by x−a leaves p(a).",
  "Rational Functions":"Factor first. Canceled denominator factors make holes; remaining denominator zeros make vertical asymptotes.",
  "Radicals":"√(a·b)=√a·√b. Look for the largest perfect-square factor.",
  "Exponential Functions":"Typical form: y=a(b)ˣ. If possible, rewrite both sides with the same base.",
  "Logarithms":"logₐ(b)=x means aˣ=b.",
  "Exponentials & Logs":"logₐ(b)=x means aˣ=b.",
  "Sequences":"Arithmetic: aₙ=a₁+(n−1)d. Geometric: aₙ=a₁rⁿ⁻¹.",
  "Systems":"Set equal expressions equal, solve one variable, then substitute back.",
  "Trigonometry":"Degrees to radians: multiply by π/180."
};
function coachReply(q,text){
  let t=text.toLowerCase();
  if(/answer|walk.?through|solve it|full solution/.test(t)){exam.assisted??={};exam.assisted[q.id]=true;return`Let’s walk through this exact question:\n\n${q.explanation}\n\nNow try explaining that last step in your own words—that’s the part that makes it stick.`}
  if(/another|example|different number/.test(t))return`${COACH_EXAMPLES[q.topic]||q.lesson}\n\nTry copying those same steps on the current question.`;
  if(/formula|rule|equation/.test(t))return`${COACH_FORMULAS[q.topic]||q.lesson}\n\nThe important part is choosing the formula first, then substituting carefully.`;
  if(/first|start|hint|next step/.test(t))return`Start here: ${q.lesson}\n\nDo only the first substitution or factoring step before worrying about the final answer.`;
  if(/why|how come/.test(t))return`The reason is that each algebra step must keep both sides equivalent. For this problem: ${q.explanation}`;
  if(/simpl|confus|understand|what does|huh/.test(t))return`Super simple version: ${COACH_FORMULAS[q.topic]||q.lesson}\n\nThink of it as one small job at a time. ${COACH_EXAMPLES[q.topic]||""}`;
  if(/check|my answer|correct/.test(t))return`I can help you check the method without judging the final answer yet. Tell me what your first step was, then compare it with this hint: ${q.lesson}`;
  return`I’m an offline coach, so I’m best at questions about this ${q.topic} problem. Here’s the key idea: ${q.lesson}\n\nTry asking “explain it simpler,” “show another example,” “what’s the first step?”, or “walk me through it.”`;
}
function renderCoach(){
  let q=exam.questions[exam.index],messages=exam.chats?.[q.id]||[];
  $("#lesson").innerHTML=`<div class="coach-head"><div><h3>✦ Offline Study Coach</h3><small>${q.topic} • ask as many follow-ups as you need</small></div><button class="coach-close" type="button" aria-label="Close coach">×</button></div><div class="coach-messages">${messages.map(m=>`<div class="coach-message coach-${m.role}">${escapeHtml(m.text)}</div>`).join("")}</div><div class="coach-quick"><button type="button" data-coach="Explain it simpler">Explain it simpler</button><button type="button" data-coach="What's the first step?">First step</button><button type="button" data-coach="Show another example">Another example</button><button type="button" data-coach="Walk me through it">Full walkthrough</button></div><form class="coach-form"><input id="coachInput" aria-label="Ask the Study Coach" placeholder="Ask a follow-up question…" autocomplete="off"><button>Send</button></form><p class="coach-note">Works offline. It knows this lesson and common follow-ups, but it is not a general internet AI.</p>`;
  $("#lesson").classList.remove("hidden");$(".coach-close").onclick=()=>$("#lesson").classList.add("hidden");$(".coach-form").onsubmit=e=>{e.preventDefault();sendCoach($("#coachInput").value)};$$("[data-coach]").forEach(b=>b.onclick=()=>sendCoach(b.dataset.coach));let box=$(".coach-messages");box.scrollTop=box.scrollHeight;
}
function sendCoach(text){if(!text.trim())return;let q=exam.questions[exam.index];exam.chats??={};exam.chats[q.id]??=[];exam.chats[q.id].push({role:"user",text:text.trim()});exam.chats[q.id].push({role:"bot",text:coachReply(q,text)});data.draft=exam;save();renderCoach()}
function teach(){let q=exam.questions[exam.index];exam.hints[q.id]=true;exam.chats??={};exam.chats[q.id]??=[{role:"bot",text:`Let’s work on this together. ${q.lesson}\n\nWhat part feels confusing? You can keep asking until it makes sense.`}];data.draft=exam;save();renderCoach()}
function startTimer(){clearInterval(timerId);updateTimer();timerId=setInterval(()=>{exam.seconds--;data.draft=exam;if(exam.seconds%10===0)save();updateTimer();if(exam.seconds<=0){clearInterval(timerId);finishExam(true)}},1000)}
function updateTimer(){let m=Math.floor(exam.seconds/60),s=exam.seconds%60;$("#timer strong").textContent=`${m}:${String(s).padStart(2,"0")}`;$("#timer").classList.toggle("urgent",exam.seconds<300)}
function finishExam(timedOut=false){clearInterval(timerId);let correct=0,unassistedCorrect=0,unassistedTotal=0,topics={};exam.questions.forEach(q=>{let ok=isCorrect(q,exam.answers[q.id]);correct+=ok;topics[q.topic]??={correct:0,total:0};topics[q.topic].total++;topics[q.topic].correct+=ok;if(!exam.hints[q.id]){unassistedTotal++;unassistedCorrect+=ok}});Object.values(topics).forEach(t=>t.percent=Math.round(t.correct/t.total*100));let percent=Math.round(correct/exam.questions.length*100),result={id:Date.now(),date:new Date().toISOString(),mode:exam.mode,selectedTopic:exam.selectedTopic,questionCount:exam.questionCount,timeLimitMinutes:exam.timeLimitMinutes,score:correct,total:exam.questions.length,percent,grade:grade(percent),secondsUsed:exam.totalSeconds-exam.seconds,hints:Object.keys(exam.hints).length,assisted:Object.keys(exam.assisted||{}).length,formulaOpens:exam.formulaOpens,unassisted:unassistedTotal?Math.round(unassistedCorrect/unassistedTotal*100):0,topics,answers:exam.answers,hinted:exam.hints,questions:exam.questions.map(q=>q.id),timedOut};data.history.unshift(result);data.draft=null;save();renderResults(result);showView("results")}
function renderResults(r){let bestie=data.profile.voice==="bestie",weak=Object.entries(r.topics).sort((a,b)=>a[1].percent-b[1].percent)[0]?.[0];$("#resultTitle").textContent=bestie?(r.percent>=80?"Okayyy, you cooked.":"Practice data acquired ✨"):"Exam complete.";$("#resultMessage").textContent=bestie?`${data.profile.name}, you scored ${r.percent}%. ${weak} was the spicy bit today, so that’s our next glow-up target.`:`${data.profile.name}, you scored ${r.percent}%. Your next recommended focus is ${weak}.`;$("#resultPercent").textContent=`${r.percent}%`;$("#resultGrade").textContent=r.grade;$(".score-ring").style.setProperty("--score",`${r.percent*3.6}deg`);let mins=Math.floor(r.secondsUsed/60),secs=r.secondsUsed%60;$("#statCards").innerHTML=stats([["Points",`${r.score} / ${r.total}`],["Time used",`${mins}:${String(secs).padStart(2,"0")}`],["Hints / assisted",`${r.hints} / ${r.assisted||0}`],["Unassisted",`${r.unassisted}%`]]);$("#topicBreakdown").innerHTML=Object.entries(r.topics).map(([n,t])=>topicRow(n,t.percent)).join("");$("#nextSteps").innerHTML=Object.entries(r.topics).sort((a,b)=>a[1].percent-b[1].percent).slice(0,3).map(([n,t])=>`<div class="next-step"><strong>${n}</strong><span>${t.percent<60?"Relearn the core method, then try an easier example.":t.percent<80?"Do two focused practice questions.":"Keep it fresh with spaced review."}</span></div>`).join("");$("#reviewList").innerHTML=exam.questions.map((q,i)=>{let a=r.answers[q.id]||"No answer",ok=isCorrect(q,a);return `<div class="review-item"><p class="${ok?"correct-text":"wrong-text"}"><strong>${i+1}. ${ok?"Correct":"Review"} — ${q.topic}</strong></p><p>${q.prompt}</p><p>Your answer: ${escapeHtml(a)} · Correct answer: ${Array.isArray(q.answer)?q.answer[0]:q.answer}</p><p>${q.explanation}</p></div>`}).join("");$("#reviewList").classList.add("hidden");$("#toggleReview").textContent="Show review"}
function stats(items){return items.map(([a,b])=>`<div class="stat-card"><small>${a}</small><strong>${b}</strong></div>`).join("")}
function topicRow(n,p){return `<div class="topic-row"><span>${n}</span><div class="mini-bar"><i style="width:${p}%"></i></div><b>${p}%</b></div>`}
function renderDashboard(){let h=data.history,name=data.profile.name||"Student";$("#dashboardTitle").textContent=h.length?`${name}, you're building momentum.`:"Your progress starts here.";let avg=h.length?Math.round(h.reduce((s,x)=>s+x.percent,0)/h.length):0,best=h.length?Math.max(...h.map(x=>x.percent)):0,streak=h.length;$("#dashboardStats").innerHTML=stats([["Exams completed",h.length],["Average score",`${avg}%`],["Personal best",`${best}%`],["Practice streak",`${streak} day${streak===1?"":"s"}`]]);let recent=[...h].slice(0,10).reverse();$("#scoreChart").innerHTML=recent.length?recent.map((r,i)=>`<div class="chart-col"><div class="chart-bar" style="height:${Math.max(r.percent*1.8,5)}px"><span>${r.percent}</span></div>D${h.length-recent.length+i+1}</div>`).join(""):`<p class="fine-print">Complete your first exam to see a trend.</p>`;let aggregate={};h.forEach(r=>Object.entries(r.topics).forEach(([n,t])=>{aggregate[n]??={c:0,n:0};aggregate[n].c+=t.correct;aggregate[n].n+=t.total}));$("#masteryList").innerHTML=Object.keys(aggregate).length?Object.entries(aggregate).sort((a,b)=>a[0].localeCompare(b[0])).map(([n,t])=>topicRow(n,Math.round(t.c/t.n*100))).join(""):`<p class="fine-print">Topic mastery will appear after your first exam.</p>`;$("#historyList").innerHTML=h.length?h.slice(0,8).map((r,i)=>`<div class="history-row"><strong>Exam ${h.length-i}</strong><span>${new Date(r.date).toLocaleDateString()}</span><span>${r.percent}% · ${r.grade}</span></div>`).join(""):`<p class="fine-print">No saved sessions yet. Your results stay on this device.</p>`}
function topicTestResult(name,pass,detail=""){return{ name, pass, detail }}
function uniquePromptCount(questions){return new Set(questions.map(q=>q.prompt)).size}
function renderTopicTests(run=false){let summary=$("#topicTestSummary"),list=$("#topicTestResults");if(!summary||!list)return;if(!run){summary.textContent="Click “Run topic tests” to check the app.";list.innerHTML="";return}let originalLog=JSON.parse(JSON.stringify(data.generatorLog||{})),topics=allTopics(),results=[];try{results.push(topicTestResult("Topic list includes all Algebra 2 subjects",topics.length===11,`${topics.length} topics found`));for(let topic of topics){let qs=chooseTopicQuestions(topic,12,"Warm-up",{remember:false});results.push(topicTestResult(`${topic}: creates 12 unique questions`,qs.length===12&&uniquePromptCount(qs)===12,`${uniquePromptCount(qs)} unique prompts`));results.push(topicTestResult(`${topic}: keeps questions in the selected topic`,qs.every(q=>q.topic===topic),qs.map(q=>q.topic).filter(t=>t!==topic).join(", ")||"all matched"));results.push(topicTestResult(`${topic}: questions have answers and explanations`,qs.every(q=>q.answer&&q.lesson&&q.explanation&&q.prompt),"shape check"))}for(let topic of topics){data.generatorLog={usedPromptKeys:[],sessionCounter:0};let first=chooseTopicQuestions(topic,10,"Medium"),second=chooseTopicQuestions(topic,10,"Medium"),secondPrompts=new Set(second.map(q=>q.prompt)),overlap=first.filter(q=>secondPrompts.has(q.prompt));results.push(topicTestResult(`${topic}: back-to-back tests do not repeat`,overlap.length===0,`${overlap.length} repeats`))}data.generatorLog={usedPromptKeys:[],sessionCounter:0};let exponents=chooseTopicQuestions("Exponential Functions",25,"Warm-up",{remember:false}),logLeak=exponents.find(q=>/log/i.test(`${q.prompt} ${q.lesson} ${q.explanation}`));results.push(topicTestResult("Exponential Functions does not include logs",!logLeak,logLeak?.prompt||"clean"));let logs=chooseTopicQuestions("Logarithms",12,"Warm-up",{remember:false});results.push(topicTestResult("Logarithms includes actual log questions",logs.some(q=>/log base/i.test(q.prompt)),"log prompt check"));let mix=chooseQuestions();results.push(topicTestResult("Adaptive mix creates 10 unique questions",mix.length===10&&uniquePromptCount(mix)===10,`${uniquePromptCount(mix)} unique prompts`))}catch(error){results.push(topicTestResult("Test runner crashed",false,error.message))}finally{data.generatorLog=originalLog;save()}let passed=results.filter(r=>r.pass).length;summary.textContent=`${passed} / ${results.length} tests passed.`;summary.className=`test-summary ${passed===results.length?"test-pass":"test-fail"}`;list.innerHTML=results.map(r=>`<div class="test-row ${r.pass?"test-pass":"test-fail"}"><strong>${r.pass?"✓":"✕"} ${escapeHtml(r.name)}</strong><span>${escapeHtml(r.detail)}</span></div>`).join("")}
function openFormula(){if(exam){exam.formulaOpens++;data.draft=exam;save()}$("#formulaModal").showModal()}
function confirmSignOut(){let modal=$("#signOutModal");if(modal?.showModal)modal.showModal();else if(confirm("Are you sure you want to sign out?"))fb?.auth().signOut()}
function finishSignOut(){let modal=$("#signOutModal");if(modal?.close)modal.close();fb?.auth().signOut()}
function toast(s){$("#toast").textContent=s;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),1800)}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function forceAuthGate(show){let gate=$("#authGate");if(gate){gate.classList.toggle("hidden",!show);gate.style.display=show?"grid":"none";gate.setAttribute("aria-hidden",show?"false":"true")}document.body.classList.toggle("signed-in",!show);$("#signOutButton")?.classList.toggle("hidden",show)}
async function applySignedInUser(user){authUser=user;if(accountUnsub){accountUnsub();accountUnsub=null}if(!user){account=null;renderAccount();forceAuthGate(true);return}forceAuthGate(false);account=await firestoreSyncAccount();renderAccount();let ref=fb.firestore().collection("users").doc(user.uid);accountUnsub=ref.onSnapshot(snap=>{if(snap.exists){account={uid:user.uid,...snap.data()};renderAccount();let premium=account?.accountType==="premium"||account?.premiumStatus==="approved"||isAdminEmail(user.email);showAuthMessage(`${premium?"Premium/Admin":"Basic"} account loaded for ${user.email}.`)}});let premium=account?.accountType==="premium"||account?.premiumStatus==="approved"||isAdminEmail(user.email);toast(`${premium?"Premium/Admin":"Basic"} signed in`)}
async function initFirebaseAuth(){if(!firebaseConfigured()){forceAuthGate(true);showAuthMessage("Firebase is not configured yet.");return}firebase.initializeApp(window.FIREBASE_CONFIG);fb=firebase;functionsApi=firebase.functions();await firebase.auth().setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});firebase.auth().getRedirectResult().then(result=>{if(result?.user)applySignedInUser(result.user)}).catch(error=>showAuthMessage(error.message||"Google sign-in could not finish."));firebase.auth().onAuthStateChanged(user=>applySignedInUser(user).catch(error=>showAuthMessage(error.message||"Could not load your account.")));setTimeout(()=>{let user=firebase.auth().currentUser;if(user)applySignedInUser(user).catch(()=>{})},1000)}
async function signInProvider(){if(!fb)return;try{showAuthMessage("Opening Google sign-in...");await clearOldAppCache();let provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:"select_account"});let result=await firebase.auth().signInWithPopup(provider);if(result?.user)await applySignedInUser(result.user)}catch(error){if(["auth/popup-blocked","auth/popup-closed-by-user","auth/cancelled-popup-request"].includes(error.code)){showAuthMessage("Google popup was blocked or closed. Please allow popups for this site, then tap Continue with Google again. On iPhone, try Safari or Chrome directly, not an in-app browser.")}else{showAuthMessage(error.message||"Sign-in failed.")}}}
$$("[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("#setupForm").onsubmit=startExam;$("#resumeExam").onclick=resumeExam;$("#makeWorksheet").onclick=makeWorksheet;$("#printWorksheet").onclick=()=>window.print();$("#googleSignIn").onclick=()=>signInProvider("google");$("#signOutButton").onclick=confirmSignOut;$("#cancelSignOut").onclick=()=>$("#signOutModal").close();$("#staySignedIn").onclick=()=>$("#signOutModal").close();$("#confirmSignOut").onclick=finishSignOut;$("#upgradePremium").onclick=requestPremium;$("#refreshAdmin").onclick=renderAdmin;$("#themeSelect").onchange=e=>{document.documentElement.dataset.theme=e.target.value;data.profile.theme=e.target.value;save()};["examMode","topicSelect","topicDifficulty"].forEach(id=>$(`#${id}`).onchange=updateSetupMode);["topicQuestionCount","topicTestMinutes"].forEach(id=>$(`#${id}`).oninput=updateSetupMode);$("#nextButton").onclick=next;$("#prevButton").onclick=()=>{if(exam.index){exam.index--;renderQuestion()}};$("#teachButton").onclick=teach;$("#formulaTop").onclick=openFormula;$("#formulaExam").onclick=openFormula;$("#closeFormula").onclick=()=>$("#formulaModal").close();$("#exitExam").onclick=()=>{clearInterval(timerId);data.draft=exam;save();showView("home");toast("Exam saved. You can resume it from Home.")};$("#toggleReview").onclick=()=>{let x=$("#reviewList");x.classList.toggle("hidden");$("#toggleReview").textContent=x.classList.contains("hidden")?"Show review":"Hide review"};$("#clearData").onclick=()=>{if(confirm("Clear your profile and all exam results from this browser?")){localStorage.removeItem(KEY);data=load();applyProfile();renderDashboard();updateResumeButton()}};applyProfile();updateResumeButton();renderDashboard();initFirebaseAuth();if("serviceWorker"in navigator){navigator.serviceWorker.getRegistrations().then(regs=>regs.forEach(reg=>reg.unregister())).catch(()=>{})}
